name: medplum-gen - Pull Request

on: pull_request

jobs:
  test:
    name: Validate spec
    runs-on: ubuntu-latest
    steps:
    - name: Install openapi-generator-cli
      run: sudo make setup

    - uses: actions/checkout@v2

    - name: Validate
      run: make validate
