name: medplum-gen - Pull Request

on: pull_request

jobs:
  test:
    name: Validate spec
    runs-on: ubuntu-latest
    steps:
    - name: Install openapi-generator
      run: sudo apt-get update && sudo apt-get install -y openapi-generator

    - uses: actions/checkout@v2

    - name: Validate
      run: make validate
