name: medplum-gen - Release

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'norelease') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install openapi-generator
        run: sudo apt-get update && sudo apt-get install -y openapi-generator-cli

      - name: Validate
        run: make validate

      - name: Generate new tag
        uses: mathieudutour/github-tag-action@v6.1
        id: get_new_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
          tag_prefix: "libs/protos/v"
